CommunityFund/config/routes.rb
Rails.application.routes.draw do
  # devise overrides
  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}

  root "home#index"

  #dashboard
  get 'dashboard' => 'dashboard#index'
  get 'users/:username' => 'users#show', as: 'users'

  #communities
  get 'communities' => 'communities#index'
  get 'communities/:id/edit_photo' => 'communities#edit_photo'
  post 'communities/:id/join' => 'communities#join'

  namespace :admin do
    get :analytics

    get :settings
    get 'settings/autocomplete',   to: :autocomplete_user_username
    post 'settings/update_admins', to: :update_admins

    get :moderation
  end

  namespace :report do
    post :dismiss
    post :project
  end

  namespace :location do
    get :countries
    get :cities
  end

  resources :communities
  resources :projects do
    member do
      post :cancel
    end
  end
  resources :funds
  resources :posts
  resources :feedbacks do
    member do
      post :submit
      post :dismiss
    end
  end

end

CommunityFund/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :timeoutable, :omniauthable,
         omniauth_providers: [:facebook]

  validates :username, presence: true, uniqueness: true,
            format: { with: /\A[A-Za-z0-9_]+\z/,
                      message: "Only alphanumerical characters and underscores allowed." }
  

  has_and_belongs_to_many :communities
  has_many :projects
  has_many :funds
  has_many :feedbacks
  has_many :reports
  has_many :posts

  mount_uploader :avatar, AvatarUploader
  

  def in_community?(community)
    communities.include? community
  end

  def fund_for_project(project)
    funds.where(project_id: project.id).last
  end

  def has_reported?(report_type, obj_id)
    results = reports.where(reported_obj_type: report_type, reported_obj_id: obj_id)
    return (not results.blank?)
  end

  def open_feedbacks
    if feedbacks.where(:submitted => false).present?
      return true
    else
      return false
    end
  end

  def feedback_button_text
    if open_feedbacks
      "You have (#{feedbacks.where(:submitted => false).count}) projects to give feedback on"
    else
      "No feedbacks are available."
    end
  end

  def projects_funded
    Project.find(self.funds.pluck(:project_id))
  end

  def avatar_url(size = 80)
     default_url = "mm"  #"#{root_url}images/guest.png"
    if url = avatar.url
      url
    else
      gravatar_id = Digest::MD5.hexdigest(email.downcase)
      "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=#{CGI.escape(default_url)}"
    end
  end

  def geo_community
    if self.location.present?
        return GeoInfo::location_by_id(self.location)
    end

    return nil
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.name.downcase.tr(" ", "_")
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.username = data["name"].downcase.tr(" ", "_") if user.username.blank?
        user.email = data["email"] if user.email.blank?
        user.uid = data["id"]
        user.provider = "facebook"
        puts session["devise.facebook_data"]
        puts data
      end
    end
  end

  # Returns 1, 2, 3, or 4 based on Feedbacks given on initiated projects
  def average_rating
    feedbacks = Feedback.submitted.where("project_id in (?)", self.projects.pluck(:id))
    if feedbacks.count >= 1
      sum = 0
      feedbacks.each do |feedback|
        sum += feedback.rating
      end
      average_rating = (sum.to_f() / feedbacks.count).round(1)
      #return 1, 2, 3, or 4 based on average_rating
      if average_rating > 0 and average_rating <= 2.5
        average_rating = 1
      elsif average_rating > 2.5 and average_rating <= 5.0
        average_rating = 2
      elsif average_rating > 5.0 and average_rating <= 7.5
        average_rating = 3
      elsif average_rating > 7.5 and average_rating <= 10.0
        average_rating = 4
      end
    else
      average_rating = 0
    end
    average_rating
  end
  
end

CommunityFund/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :user_exists

  def show
    @projects = @user.projects.order('updated_at DESC')
    @funds = @user.funds.order('updated_at DESC')
    @communities = @user.communities.active
    # find average feedback for this user
    @average_rating = @user.average_rating
    if @user == current_user
      # Only send feedback records if the user is looking at his/her own profile
      @received_feedbacks = Feedback.where("project_id in (?)", @user.projects.pluck(:id)).where(submitted: true)
      @sent_feedbacks = @user.feedbacks.where(submitted: true)
      # Only send whether facebook is linked or not as well
      @not_linked = @user.uid.blank?
    end
  end

  def user_exists
    @user = User.find_by_username(params[:username])
    redirect_to root_path if @user.blank?
  end
end

CommunityFund/app/helpers/users_helper.rb
module UsersHelper
end

CommunityFund/app/views/users/show.html.haml
.container
  .row
    .col-lg-3.col-sm-5
      = image_tag avatar_url(@user, 300), :class => "img-thumbnail center-block"
      %h1 #{@user.username}
      %span.label.label-info.tags.badge
        - if @user.admin?
          admin
        - else
          member
      %br
      %br
      .panel.panel-default.panel-body
        %ul.list-group
          %li.list-group-item.text-right
            %span.pull-left
              %strong Full Name:
            #{@user.first_name} #{@user.last_name}
          %li.list-group-item.text-right
            %span.pull-left
              %strong Date Joined:
            #{@user.created_at.to_date}
          %li.list-group-item.text-right
            %span.pull-left
              %strong Last Login:
            #{time_ago(@user.current_sign_in_at)}
          %li.list-group-item.text-right
            %span.pull-left
              %strong Email:
            #{@user.email}
          - if !@user.facebook_url.blank?
            %li.list-group-item.text-right
              %span.pull-left
                %strong Facebook:
              = link_to "#{@user.facebook_url}", "https://www.facebook.com/" + @user.facebook_url
          - if !@user.twitter_url.blank?
            %li.list-group-item.text-right
              %span.pull-left
                %strong Twitter:
              = link_to "#{@user.twitter_url}", "https://www.twitter.com/" + @user.twitter_url
      - if @not_linked
        .panel.panel-default.panel-body
          = link_to "Link Account with Facebook", user_omniauth_authorize_path(:facebook)
      .panel.panel-default
        .panel-heading
          %strong Communities
        .panel-body.community-panel
          - if @communities.present?
            - @communities.each do |community|
              %a.span.label.label-info.tags.badge{href: community_path(community.id)} ##{community.name}
          - else
            .top-margin-sm None

    .col-lg-9.col-sm-7
      %ul.nav.nav-pills{role: "tablist"}
        %li.active{role: "presentation"}
          %a{href: "#profile", data: {toggle: 'tab'}}
            %span.glyphicon.glyphicon-user
              Profile
        %li{role: "presentation"}
          %a{href: "#projects", data: {toggle: 'tab'}}
            %span.glyphicon.glyphicon-folder-close
              Projects
        %li{role: "presentation"}
          %a{href: "#funds", data: {toggle: 'tab'}}
            %span.glyphicon.glyphicon-heart
              Funded
        - if current_user == @user
          %li{role: "presentation"}
            %a{href: "#received_feedbacks", data: {toggle: 'tab'}}
              %span.glyphicon.glyphicon-comment
                Received Feedback
          %li{role: "presentation"}
            %a{href: "#sent_feedbacks", data: {toggle: 'tab'}}
              %span.glyphicon.glyphicon-comment
                Sent Feedback

      .tab-content
        .tab-pane.fade.in.active{id: "profile"}
          .panel.panel-default
            .panel-heading
              %strong About Me
            .panel-body
              = @user.description
          .panel.panel-default
            .panel-heading
              %strong Location
            .panel-body
              %p City: #{@user.geo_community.present? ? @user.geo_community.city : 'Not Specified'}
              %p Country: #{@user.geo_community.present? ? @user.geo_community.country : 'Not Specified'}
          .panel.panel-default
            .panel-heading
              %strong Initiator Statistics
            .panel-body
              - if @average_rating == 0
                %p
                  Average rating: No feedback received :(
              - else
                = render template: "feedbacks/average_feedback", :locals => { :average_rating => @average_rating }
              %p Projects Started: #{@projects.count}
              %p Successfully Funded: #{@projects.where(:funding_successful => true).count}
              //progress bar showing reputation score based on user feedbacks
              
          .panel.panel-default
            .panel-heading
              %strong Funder Statistics
            .panel-body
              %p Projects Funded: #{@funds.count}
              %p= "Total Amount Funded: $#{number_with_precision(@funds.sum(:amount), precision: 2)}"
              %p= "Average Amount Funded: $#{number_with_precision(@funds.present? ? @funds.average(:amount) : '0.0', precision: 2)}"
        .tab-pane.fade{id: "projects"}
          - if @projects.count == 0
            .panel.panel-default
              .panel-body
                #{@user.username} hasn't started any projects yet.
          - else
            - @projects.each do |p|
              - unless p.closed?
                .panel.panel-success
                  .panel-heading
                    .panel-title.community
                      - if p.banner?
                        .project-banner-community
                          = image_tag p.banner.url
                      %h3 
                        = p.name
                      Created: #{p.created_at.to_date}
                      .pull-right Updated: #{time_ago(p.updated_at)}
                  .panel-body
                    = p.description
                    %br
                    .pull-right
                      = link_to 'Details', project_path(p.id)
              - else
                .panel.panel-danger
                  .panel-heading
                    .panel-title.community
                      - if p.banner?
                        .project-banner-community
                          = image_tag p.banner.url
                      %h3 
                        = p.name
                      Created: #{p.created_at.to_date}
                    .pull-right Updated: #{time_ago(p.updated_at)}
                  .panel-body
                    = p.description
                    %br
                    .pull-right
                      = link_to 'Details', project_path(p.id)
        .tab-pane.fade{id: "funds"}
          - if @funds.count == 0
            .panel.panel-default
              .panel-body
                #{@user.username} hasn't funded any projects yet.
          - else
            - @funds.each do |f|
              - unless f.project.closed?
                .panel.panel-success
                  .panel-heading
                    .panel-title.community
                      - if f.project.banner?
                        .project-banner-community
                          = image_tag f.project.banner.url
                      %h3 
                        = f.project.name
                      .text-right
                        Donated $#{number_with_precision(f.amount, precision: 2)} #{time_ago(f.updated_at)}
                  .panel-body
                    %strong Reward:
                    %br
                    = f.reward.present? ? "#{f.reward.description}" : "None"
                    %br
                    .pull-right
                      = link_to 'Details', project_path(f.project.id)
              - else
                .panel.panel-danger
                  .panel-heading
                    .panel-title.community
                      - if f.project.banner?
                        .project-banner-community
                          = image_tag f.project.banner.url
                      %h3 
                        = f.project.name
                      .text-right
                        Donated $#{number_with_precision(f.amount, precision: 2)} #{time_ago(f.updated_at)}
                  .panel-body
                    %strong Reward:
                    %br
                    = f.reward.present? ? "#{f.reward.description}" : "None"
                    %br
                    .pull-right
                      = link_to 'Details', project_path(f.project.id)
        .tab-pane.fade{id: "received_feedbacks"}
          .list-group
            - if @received_feedbacks.present?
              - @received_feedbacks.each do |feedback|
                .panel.panel-default
                  .panel-body
                    .pull-left
                      = image_tag avatar_url(feedback.user, 100), class: 'img-circle avatar'
                    %h4
                      = link_to "#{feedback.user.username}", users_path(feedback.user.username)
                      on
                      = link_to "#{feedback.project.name}", project_path(feedback.project.id)
                    
                    %p #{feedback.description}
                    Rating: #{feedback.rating}
                    .pull-right #{time_ago(feedback.updated_at)}
            - else
              .panel.panel-default.panel-body No feedback received.
        .tab-pane.fade{id: "sent_feedbacks"}
          .list-group
            - if @sent_feedbacks.present?
              - @sent_feedbacks.each do |feedback|
                .panel.panel-default
                  .panel-body
                    %h4
                      = link_to "#{feedback.project.name}", project_path(feedback.project.id)
                    
                    %p #{feedback.description}
                    Rating: #{feedback.rating}
                    .pull-right #{time_ago(feedback.updated_at)}
            - else
              .panel.panel-default.panel-body No feedback sent.