CommunityFund/config/routes.rb
Rails.application.routes.draw do
  # devise overrides
  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}

  root "home#index"

  #dashboard
  get 'dashboard' => 'dashboard#index'
  get 'users/:username' => 'users#show', as: 'users'

  #communities
  get 'communities' => 'communities#index'
  get 'communities/:id/edit_photo' => 'communities#edit_photo'
  post 'communities/:id/join' => 'communities#join'

  namespace :admin do
    get :analytics

    get :settings
    get 'settings/autocomplete',   to: :autocomplete_user_username
    post 'settings/update_admins', to: :update_admins

    get :moderation
  end

  namespace :report do
    post :dismiss
    post :project
  end

  namespace :location do
    get :countries
    get :cities
  end

  resources :communities
  resources :projects do
    member do
      post :cancel
    end
  end
  resources :funds
  resources :posts
  resources :feedbacks do
    member do
      post :submit
      post :dismiss
    end
  end

end

CommunityFund/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :authenticate_user!

  #creates @dashboard instance variable which is a list that stores hashs of differen  @dashboard which fill the dash
  def index
    @dashboard = []

    #Project they are interested in has started, or reached milestones

    #grab all communities, grab all *unique* projects
    unique_projects = []

    current_user.communities.each do |f|
      f.projects.each do |p|
        if unique_projects.include?(p) == false
          unique_projects << p
        end
      end
    end

    unique_projects.each do |p|
      p.milestones.each do |m|
        if m.milestone_type == "Fund"
          if Fund.find(m.fund_id).user_id.present?
            event = {name: p.name, type_id: p.id, time: m.created_at, description: m.description, username: User.find(Fund.find(m.fund_id).user_id).username}
            @dashboard.push(event)
          end
        elsif m.milestone_type == "Feedback" or m.milestone_type == nil
          event = {name: p.name, type_id: p.id, time: m.created_at, description: m.description}
          @dashboard.push(event)
        end
      end
    end

    #projects located near them has started
    Project.near_user(current_user).each do |p|
      event = {name: p.name, type_id: p.id, description: "Project has been started in your area!", time: p.created_at}
      @dashboard.push(event)
    end

    @dashboard = @dashboard.sort_by { |k| k[:time] }
    @dashboard.reverse!
    @dashboard = @dashboard.paginate(:page => params[:page], :per_page => 15)

    respond_to do |format|
      format.html
      format.js
    end

  end
end

CommunityFund/app/helpers/dashboard_helper.rb
module DashboardHelper
end

CommunityFund/app/views/dashboard/_event.html.haml
- event.each do |e|
  .panel.panel-default
    .panel-heading
      .panel-title{id:"dashboard"}
        %h2
          = link_to(e[:name] + " update!", project_path(e[:type_id]))
    .panel-body{id:"dashboard"}
      %p
        = e[:description]
    .panel-footer
      %p
        //link to user public profile page
        - if e[:username]
          = link_to e[:username] + " made the donation at " + e[:time].to_s, '/users/' + e[:username]
        - else
          = e[:time].strftime("%B %d, %Y")    

CommunityFund/app/views/dashboard/collect_information.html.haml
.row
  .col-md-offset-3.col-md-6
    .panel.panel-default
      .panel-heading
        %h1.panel-title.text-center Mind if we grab some more information from you?
      .panel-body
        = simple_form_for @collect_information_form, url: dashboard_submit_information_path, input_html: {class: 'form-horizontal'} do |f|
          .form-group
            = f.error_notification

          .panel-group
            .panel.panel-default
              .panel-heading
                %h4.panel-title Considering joining any of these communities?
              .panel-body
                %ul.list-group
                  - @communities.each do |community|
                    .checkbox
                      %label
                        = f.check_box "community_#{community.id}".to_sym, required: false, as: :boolean
                        = community.name
          .form-actions
            = f.button :submit, "Submit", id: "submit_button", class: 'btn btn-primary'
            = link_to "Do this later", dashboard_path, class: 'btn btn-sm', id: "do_this_later"

CommunityFund/app/views/dashboard/index.html.haml
.containertype_id
  .row
    %h1{style:"text-align:center;"} Dashboard
    %br
    .col-sm-9.col-md-9
      - if !current_user
        %p
          sign in to see some cool stuff yo
      - else
        - if @dashboard.count > 0
          #events
            = render partial: "event", locals: {event: @dashboard}
          #infinite-scrolling
            = will_paginate
        - else
          .panel.panel-default
            .panel-heading
              .panel-title
                %h3{class: "panel-title"}
                  Go join some communities!
            .panel-body
              %p Are you a robot? Go join communities!

    //sidebar panels

    //communities
    .col-sm-3.col-md-3
      .panel.panel-default
        - if current_user.communities.length >= 1
          .panel-heading
            .panel-title
              = link_to "Browse all communities", communities_path
        - else
          .panel-heading
            .panel-title
              %p
                Hey, you haven't joined any communities yet!
          .panel-body{:style => "text-align: center;" }
            = link_to "Wanna?", edit_user_registration_path
      .panel.panel-default
        .panel-heading
          .panel-title
            %h4 Projects you have funded:
        .panel-body
          - if current_user.projects_funded.count > 5
            %ul
            - current_user.projects_funded[0 .. 5].each do |p|
              %li
                = link_to p.name, project_path(p.id)
            %p ... and more!
          - elsif current_user.projects_funded.count >= 1
            %ul
            - current_user.projects_funded[0 .. 5].each do |p|
              %li
                = link_to p.name, project_path(p.id)
          - else
            No projects have yet been funded.
      .panel.panel-default
        .panel-heading
          .panel-title
            %h4 Projects you have started:
        .panel-body
          - if current_user.projects.count >= 1
            %ul
            - current_user.projects.each do |p|
              %li
                = link_to p.name, project_path(p.id)

          - else
            No projects have been started.
      .panel.panel-default
        .panel-heading
          .panel-title
            %h4 Give Feedbacks to finished projects:
        .panel-body
          - if current_user.open_feedbacks
            %i{class:"fa fa-exclamation-circle"}
            = link_to current_user.feedback_button_text, feedbacks_path
          - else
            = current_user.feedback_button_text
        .panel-footer
          - if current_user.feedbacks.count >= 1
            //TODO: dismiss button will be here

CommunityFund/app/views/dashboard/index.js.erb
$('#events').append('<%= j render partial: "event", locals: {event: @dashboard} %>');
<% if @dashboard.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @dashboard %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>