CommunityFund/config/routes.rb
Rails.application.routes.draw do
  # devise overrides
  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}

  root "home#index"

  #dashboard
  get 'dashboard' => 'dashboard#index'
  get 'users/:username' => 'users#show', as: 'users'

  #communities
  get 'communities' => 'communities#index'
  get 'communities/:id/edit_photo' => 'communities#edit_photo'
  post 'communities/:id/join' => 'communities#join'

  namespace :admin do
    get :analytics

    get :settings
    get 'settings/autocomplete',   to: :autocomplete_user_username
    post 'settings/update_admins', to: :update_admins

    get :moderation
  end

  namespace :report do
    post :dismiss
    post :project
  end

  namespace :location do
    get :countries
    get :cities
  end

  resources :communities
  resources :projects do
    member do
      post :cancel
    end
  end
  resources :funds
  resources :posts
  resources :feedbacks do
    member do
      post :submit
      post :dismiss
    end
  end

end

CommunityFund/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :communities
  has_many :rewards
  has_many :funds
  has_many :feedbacks
  has_many :milestones
  has_many :posts

  mount_uploader :banner, AvatarUploader

  accepts_nested_attributes_for :rewards, reject_if: :all_blank, allow_destroy: true

  scope :open, -> { where(open: true)}
  scope :successfully_closed, -> { where(open: false, funding_successful: true)}

  def initiator
    user
  end

  def self.minimum_start_year
    DateTime.now.year
  end

  def self.maximum_end_year
    DateTime.now.year + 10
  end

  def self.near_user(u)
    if u.location.blank?
      return []
    end
  
    Project.all.where("geo_communities_str LIKE '%#{u.location}%'")
  end

  def donors
    User.where('id in (?)', funds.pluck(:user_id))
  end

  def description_lead
    if %w(a e i o u).member? self.communities.first.name[0].downcase
      "An"
    else
      "A"
    end
  end

  def is_initiator?(user)
    initiator.try(:id) == user.id
  end

  def hashtag_community(community)
    "##{community.name.gsub(/ /, "")}"
  end

  def completion_date_for_display
    "At midnight on #{completion_date.strftime('%B %m, %Y')}"
  end

  def closed?
    !open?
  end

  def percentage_completed
    self.total_amount/self.target_amount
  end

  # Returns a string containing the project status
  def completion_status
    returnValue = {status: '' , percentage: 0.0}
    #status
    if self.target_amount and self.total_amount
      twenty_five = self.target_amount*0.25
      fifty = self.target_amount*0.5
      seventy_five = self.target_amount*0.75
      if self.total_amount.to_s.to_i > seventy_five
        returnValue[:percentage] = 0.75
        returnValue[:status] = "Project is almost funded! (Over 75% funded)"
      elsif self.total_amount.to_s.to_i > fifty
        returnValue[:percentage] = 0.50
        returnValue[:status] = "Project is half way there! (Over 50% funded)"
      elsif self.total_amount.to_s.to_i >= twenty_five
        returnValue[:percentage] = 0.25
        returnValue[:status] = "Project is starting to shape up! (Over 25% funded)"
      elsif self.total_amount.to_s.to_i < twenty_five
        returnValue[:percentage] = 0.01
        returnValue[:status] = "Project has got its first donation! (0-25% funded)"
      else
        returnValue[:percentage] = 0.0
        returnValue[:status] = "Project has no funding!"
      end
      returnValue
    else
      nil
    end

  end

  def total_amount
    self.funds.sum(:amount)
  end

  def funding_successful?
    self.total_amount >= self.target_amount
  end

  def close!
    self.open = false
    if funding_successful?
      self.funding_successful = true
      notify_users_on_funding!
    end

    self.save
  end

  def cancel!
    self.open = false
    self.funding_successful = false
    self.save
  end

  def geo_communities
    geo_ids = self.geo_communities_str.split(',').map(&:to_i)
    GeoInfo::locations_by_ids(geo_ids)
  end

  def average_rating
    submitted_feedback = Feedback.submitted.where(project_id: self.id)
    if submitted_feedback.count >= 1
      submitted_feedback.sum(:rating) / submitted_feedback.count
    else
      0
    end
  end

  # Returns 1, 2, 3, or 4 based on Feedbacks given on this project
  def feedback_score
    average_rating = self.average_rating
    if average_rating > 0 and average_rating <= 2.5
      average_rating = 1
    elsif average_rating > 2.5 and average_rating <= 5.0
      average_rating = 2
    elsif average_rating > 5.0 and average_rating <= 7.5
      average_rating = 3
    elsif average_rating > 7.5 and average_rating <= 10.0
      average_rating = 4
    end
  end

  private

    def notify_users_on_funding!
      # loop through all funding users
      # build a feedback object for each one
      donors.each do |donor|
        Feedback.create(
            user_id: donor.id,
            project_id: self.id,
            submitted: false,
            rating: 0,
            description: "",
            dismissed: false
          )
      end
    end
end

CommunityFund/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!, except: [:show]
  before_filter :ensure_initiator, only: [:edit, :update, :cancel]
  before_filter :ensure_open, only: [:edit, :update, :cancel]

  def new
    country_data = GeoInfo::countries.map { |c| [c.country, c.id] }
    @countries = Hash[*country_data.flatten]
    @communities = Community.active
    @new_project_form = ::NewProjectForm.new(user: current_user, communities: @communities)
    @project = @new_project_form.project
  end

  def create
    @communities = Community.active
    @new_project_form = ::NewProjectForm.new(user: current_user, communities: @communities)
    @new_project_form.submit(params)
    @project = @new_project_form.project
    Milestone.create(:project_id => @project.id, :percentage => 0.0, :fund_id => nil, :description => 'Project has been initiated!')
    redirect_to project_path(id: @project.id)
  end

  def index
    @projects = current_user.projects
  end

  def show
    @project = Project.find(params[:id])
    @rewards = @project.rewards.order('reward_level ASC')
    @fund = current_user.try(:fund_for_project, @project)

    @posts = @project.posts.paginate(page: params[:page], per_page: 15).order("updated_at DESC")
    if params.has_key?(:new_fund_id)
      @new_fund = true
    end
  end

  def edit
    @communities = Community.active
    @edit_project_form = ::EditProjectForm.new(user: current_user, communities: @communities, project: @project)
  end

  def update
    @communities = Community.active
    @edit_project_form = ::EditProjectForm.new(user: current_user, communities: @communities, project: @project)
    @edit_project_form.submit(params)
    redirect_to project_path(id: @project.id)
  end

  def cancel
    @project.cancel!
    render nothing: true
  end

  private
    def ensure_open
      @project ||= Project.find(params[:id])
      if @project.closed?
        redirect_to project_path(id: @project.id)
      end
    end

    def ensure_initiator
      @project = Project.find(params[:id])
      initiator_or_admin = (current_user.id == @project.initiator.id) || current_user.admin?
      if (not initiator_or_admin) || @project.closed?
        # TODO get this working
        flash[:error] = "Permission Denied"
        redirect_to project_path(id: @project.id)
      end
    end
end

CommunityFund/app/helpers/project_helper.rb
module ProjectHelper
  def user_has_funded?
    current_user.funds.where(project_id: @project.id).present?
  end
end

CommunityFund/app/views/projects/_action_button.html.haml
.action-buttons
  - if @project.open?
    - if current_user.present? && @project.is_initiator?(current_user)
      = link_to "Edit Project", edit_project_path(id: @project.id), id: "edit_button", class: "btn btn-lg btn-primary action-button"
      = link_to "Cancel Project", cancel_project_path(id: @project.id), id: "cancel_button", class: "btn btn-lg action-button btn-danger cancel-button", data: {:'project-id' => @project.id, toggle: 'modal', target: '#cancel-modal'}
    - elsif user_signed_in?
      - if user_has_funded?
        = link_to "Edit donation", edit_fund_path(id: @fund.id, project_id: @project.id), id: 'edit_funding_button', class: 'btn btn-lg btn-primary action-button funding-button'
      - else
        = link_to "Fund this", new_fund_path(project_id: @project.id), id: 'funding_button', class: "btn btn-lg btn-primary action-button funding-button"
    - else # not logged in, let's get them to sign up!
      = link_to "Sign up to fund this", new_user_registration_path, class: 'btn btn-lg btn-primary action-button'
  - else
    .btn.btn-lg.action-button.disabled
      Project Closed

#cancel-modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button{ class: 'close', data: { dismiss: 'modal' } } &times;
        %h4 Close Project

      .modal-body
        %p Are you sure you wish to cancel this project?
        %p Once you close this project, it will remain closed to good. No funds will go through and you will not be responsible for fulfilling any rewards.

      .modal-footer
        %button{ class: 'btn btn-default', data: { dismiss: 'modal' } } Dismiss
        %button{ class: 'btn btn-danger cancel-confirm-btn', data: { dismiss: 'modal' } } Cancel Project

CommunityFund/app/views/projects/_moderate_buttons.html.haml
- if user_signed_in?
	- if current_user.admin?
		// Edit button (for admins)
		= link_to "Edit as Administrator", edit_project_path(id: @project.id), id: "edit_button", class: "btn btn-danger edit-btn"

	- elsif not current_user.has_reported?('project', @project.id)
		// Report button
		.btn.btn-danger.report-btn{ data: { :'project_id' => @project.id, toggle: 'modal', target: '#report-modal' } }
			Report Project

		// Report modal
		#report-modal.modal.fade
			.modal-dialog
				.modal-content
					.modal-header
						%button{ class: 'close', data: { dismiss: 'modal' } }
							&times;
						%h4
							Report project

					.modal-body
						%p
							Are you sure you wish to report this content as offensive or inappropriate?
						%p
							Upon submission the CommunityFund administrators will be notified and will conduct a review of this project.

					.modal-footer
						%button{ class: 'btn btn-default', data: { dismiss: 'modal' } }
							Cancel
						%button{ class: 'btn btn-danger report-confirm-btn', data: { dismiss: 'modal' } }
							Report

CommunityFund/app/views/projects/_reward_fields.html.haml
.nested-fields
  .list-group-item.reward-group
    .form-group
      %label{for: 'reward_level'} Amount
      .input-group
        = f.text_field :reward_level, required: true, class: 'form-control reward-level', placeholder: '$ CAD'
        %span.input-group-addon
          $
      %label{for: 'description'} Reward
      .input-group
        = f.text_field :description, required: true, class: 'form-control reward-description', placeholder: "What will the donor receive?"
        %span.input-group-addon
          %span.glyphicon.glyphicon-asterisk
      .input-group
        = link_to_remove_association "Remove Reward", f

CommunityFund/app/views/projects/edit.html.haml
.row
  %h2= "Edit #{@project.name}"
.row
  = simple_form_for @project do |f|
    .col-lg-8

      .form-group
        - if f.error_notification.present?
          .alert.alert-warning
            = f.error_notification
        %label{for: 'project_title'} Project Title
        .input-group
          = f.text_field :name, required: true, class: 'form-control'
          %span.input-group-addon
            %span#name_icon.glyphicon.glyphicon-asterisk
        .error-text#name_error.hidden
          Please enter a name
      .form-group
        %label{for: 'project_title'} Description
        .input-group
          = f.text_area :description, required: true, class: 'form-control', rows: 5, placeholder: "Why should people choose to fund you?"
          %span.input-group-addon
            %span#description_icon.glyphicon.glyphicon-asterisk
        .error-text#description_error.hidden
          Please enter a description
      .form-group
        %label{for: 'target_amount'} Target Amount
        .input-group
          = f.text_field :target_amount, requied: true, class: 'form-control', placeholder: "$ CAD"
          %span.input-group-addon
            %span#target_amount_icon.fa.fa-money
        .error-text#target_amount_error.hidden
          Please enter an amount greater than $100
      .form-group
        %label{for: 'project_completion_date'} 
          Completion Date
          %span#completion_date_icon.fa.fa-check.hidden
        .form-inline
          = f.input :completion_date, as: :date, required: true, class: 'form-control', start_year: Project.minimum_start_year, end_year: Project.maximum_end_year, order: [:day, :month, :year], label: false
        .error-text#completion_date_error.hidden
          Must be at least 1 week from now

      .banner
        .form-group
          .panel.panel-primary
            .panel-heading Banner Image This can be a logo or an informative graphic about your project.
            .panel-body
              .hint-text#banner-hint
                This is optional, but for best display please ensure banner is at least 700px in width and 400px in height.
                = f.input :banner, as: :image_preview, required: false, class: 'form-control btn', label: false, input_html: {preview_version: :thumb}

      #rewards
        .form-group
          .panel.panel-primary
            .panel-heading Reward Levels
            .panel-body
              .error-text#rewards_error.hidden
                Please finish filling out rewards
              %ul.list-group
                = f.simple_fields_for :rewards do |reward|
                  = render 'reward_fields', f: reward, show_ids: true
                .links
                  = link_to_add_association 'Add Reward Level', f, :rewards

      -# TODO banner

      = f.button :submit, "Save", id: 'save_button', class: 'btn btn-info pull-right' 

:coffeescript
  $ ->
    $("select").addClass('form-control')
    $('#project_completion_date_3i').val((new Date().getDate() + 7).toString())

  $('form').submit (event) ->
    if valid_content($('#project_name')) && valid_content($('#project_description')) && valid_amount($("#project_target_amount")) && valid_date && valid_rewards()
      return true
    else
      event.preventDefault()
      empty_content_validator(valid_content($('#project_name')), $('#project_name'), '#name_icon', '#name_error')
      empty_content_validator(valid_content($('#project_description')), $('#project_description'), '#description_icon', '#description_error')
      money_validator(valid_amount($('#project_target_amount')), $('#project_target_amount'), '#target_amount_icon', '#target_amount_error')
      date_validator(valid_date(), '#completion_date_error')
      reward_validator(valid_rewards())

  $('#project_name').bind 'input', ->
    empty_content_validator(valid_content($(this)), $(this), '#name_icon', '#name_error')
    
  $('#project_description').bind 'input', ->
    empty_content_validator(valid_content($(this)), $(this), '#description_icon', '#description_error')

  $('#project_target_amount').bind 'input', ->
    money_validator(valid_amount($(this)), $(this), '#target_amount_icon', '#target_amount_error')

  $('#project_completion_date_3i, #project_completion_date_2i, #project_completion_date_1i').change ->
    date_validator(valid_date(), '#completion_date_error')

  valid_content = (ref) ->
    if ref.val() == ""
      return false
    else
      return true

  valid_amount = (ref) ->
    num = parseInt(ref.val())
    if (num >= 100) && !(isNan(num))
      return true
    else
      return false

  valid_date =->
    day = parseInt($('#project_completion_date_3i').val())
    month = parseInt($('#project_completion_date_2i').val())
    year = parseInt($('#project_completion_date_1i').val())

    current_date = new Date()

    # apparently month is zero ordered??
    if (new Date(year, month - 1, day) < new Date(current_date.getFullYear(), current_date.getMonth(), current_date.getDate() + 7))
      return false
    else
      return true

  valid_rewards =->
    reward_groups = $('.reward-group')

    if reward_groups == undefined
      return true
    else
      is_valid = true
      for reward in reward_groups
        do ->
          if ($(reward).find('.reward-level').val() == "") || ($(reward).find('.reward-description').val() == "")
            is_valid = false

      return is_valid

  reward_validator = (value) ->
    if value
      $('#rewards_error').addClass('hidden')
    else
      $('#rewards_error').removeClass('hidden')

  empty_content_validator = (value, ref, icon, error_text) ->
    if value
      ref.removeClass('has-error')
      $(error_text).addClass('hidden')
      field_span = ref.parent().find(icon)
      field_span.removeClass("glyphicon glyphicon-asterisk fa fa-exclamation-circle")
      field_span.addClass("fa fa-check")
    else
      ref.addClass('has-error')
      $(error_text).removeClass('hidden')
      field_span = ref.parent().find(icon)
      field_span.removeClass("glyphicon glyphicon-asterisk fa fa-check")
      field_span.addClass("fa fa-exclamation-circle")

  money_validator = (value, ref, icon, error_text) ->
    if value
      ref.removeClass('has-error')
      $(error_text).addClass('hidden')
      field_span = ref.parent().find(icon)
      field_span.removeClass("has-money-error")
      field_span.addClass("correct-money")
    else
      ref.addClass('has-error')
      $(error_text).removeClass('hidden')
      field_span = ref.parent().find(icon)
      field_span.removeClass("correct-money")
      field_span.addClass("has-money-error")

  date_validator = (value, error_text) ->
    if value
      $('#completion_date_icon').addClass('fa fa-check hidden')
      $('#completion_date_icon').removeClass('fa fa-exclamation-circle')
      $('#project_completion_date_3i, #project_completion_date_2i, #project_completion_date_1i').removeClass('has-error-select')
      $(error_text).addClass('hidden')
    else
      $('#completion_date_icon').removeClass('fa fa-check')
      $('#completion_date_icon').addClass('fa fa-exclamation-circle')
      $('#project_completion_date_3i, #project_completion_date_2i, #project_completion_date_1i').addClass('has-error-select')
      $(error_text).removeClass('hidden')

CommunityFund/app/views/projects/index.html.haml
- if user_logged_in?
  /show projects that are closer to this user by geographic location maybe?
  - @projects.each do |p|
    = link_to p.name, project_path(p)
- else
  /show all

CommunityFund/app/views/projects/new.html.haml
.row
  %h2 Create a New Project
.row
  = simple_form_for @project, url: projects_path do |f|
    .col-lg-8

      .form-group
        - if f.error_notification.present?
          .alert.alert-warning
            = f.error_notification
        %label{for: 'project_name'} Project Title
        .input-group
          = f.text_field :name, required: true, class: 'form-control'
          %span.input-group-addon
            %span#name_icon.glyphicon.glyphicon-asterisk
        .error-text#name_error.hidden
          Please enter a name
      .form-group
        %label{for: 'project_description'} Description
        .input-group
          = f.text_area :description, required: true, class: 'form-control', rows: 5, placeholder: "Why should people choose to fund you?"
          %span.input-group-addon
            %span#description_icon.glyphicon.glyphicon-asterisk
        .error-text#description_error.hidden
          Please enter a description
      .form-group
        %label{for: 'target_amount'} Target Amount
        .input-group
          = f.text_field :target_amount, required: true, class: 'form-control', placeholder: "$ CAD, $100 minimum"
          %span.input-group-addon
            %span#target_amount_icon.fa.fa-money
        .error-text#target_amount_error.hidden
          Please enter an amount greater than $100
      .form-group
        %label{for: 'project_completion_date'}
          Completion Date
          %span#completion_date_icon.fa.fa-check.hidden
        .form-inline
          = f.input :completion_date, as: :date, required: true, class: 'form-control', start_year: Project.minimum_start_year, end_year: Project.maximum_end_year, order: [:day, :month, :year], label: false
        .error-text#completion_date_error.hidden
          Must be at least 1 week from now

      #communities
        .form-group
          .panel.panel-primary
            .panel-heading Which Communities is your project involved with? Please select at least one.
            .panel-body
              .error-text#communities_error.hidden
                Please select at least one community
              %ul.list-group.communities
                - @communities.each do |community|
                  .checkbox.community-box
                    %label
                      = check_box_tag "community_#{community.id}", true, class: 'form-control'
                      = community.name

      #geo-communities
        .form-group
          .panel.panel-primary
            .panel-heading
              Which areas is your project relevant to? (optional)
            .panel-body
              %table.geo-communities
                %tr.location-select
                  %td= select_tag "geo_community[][country]", options_for_select(@countries), prompt: 'ENTIRE WORLD', class: 'country-select'
                  %td= select_tag "geo_community[][city]", options_for_select([], nil), prompt: '----------', disabled: true, class: 'city-select'
                  %td= link_to '&times;'.html_safe, '#', class: 'remove-geo-community-btn'
              = link_to 'Add country or city', '#', class: 'add-geo-community-btn'

      .banner
        .form-group
          .panel.panel-primary
            .panel-heading Banner Image. This can be a logo or an informative graphic about your project.
            .panel-body
              .hint-text#banner-hint
                This is optional, but for best display please ensure banner is at least 700px in width and 400px in height.
                = f.input :banner, as: :image_preview, required: false, class: 'form-control btn', label: false, input_html: {preview_version: :thumb}

      #rewards
        .form-group
          .panel.panel-primary
            .panel-heading Reward Levels
            .panel-body
              .error-text#rewards_error.hidden
                Please finish filling out rewards
              %ul.list-group
                = f.simple_fields_for :rewards do |reward|
                  = render 'reward_fields', f: reward
                .links
                  = link_to_add_association 'Add Reward Level', f, :rewards

      

      = f.button :submit, "Submit", id: 'submit_button', class: 'btn btn-info pull-right'

:coffeescript
# validation for both project/new and project/edit

jQuery ->
  $ ->
    $("select").addClass('form-control')
    $('.checkbox').find('input').attr('checked', false)
    $('#project_completion_date_3i').val((new Date().getDate() + 7).toString())

  $('form').submit (event) ->
    if valid_content($('#project_name')) && valid_content($('#project_description')) && valid_amount($("#project_target_amount")) && valid_date && valid_communities() && valid_rewards()
      return true
    else
      event.preventDefault()
      empty_content_validator(valid_content($('#project_name')), $('#project_name'), '#name_icon', '#name_error')
      empty_content_validator(valid_content($('#project_description')), $('#project_description'), '#description_icon', '#description_error')
      money_validator(valid_amount($('#project_target_amount')), $('#project_target_amount'), '#target_amount_icon', '#target_amount_error')
      date_validator(valid_date(), '#completion_date_error')
      communities_validator(valid_communities())
      reward_validator(valid_rewards())

  $('#project_name').bind 'input', ->
    empty_content_validator(valid_content($(this)), $(this), '#name_icon', '#name_error')

  $('#project_description').bind 'input', ->
    empty_content_validator(valid_content($(this)), $(this), '#description_icon', '#description_error')

  $('#project_target_amount').bind 'input', ->
    money_validator(valid_amount($(this)), $(this), '#target_amount_icon', '#target_amount_error')

  $('#project_completion_date_3i, #project_completion_date_2i, #project_completion_date_1i').change ->
    date_validator(valid_date(), '#completion_date_error')

  $('.community-box').change ->
    communities_validator(valid_communities())

  valid_content = (ref) ->
    if ref.val() == ""
      return false
    else
      return true

  valid_amount = (ref) ->
    num = parseInt(ref.val())
    if (num >= 100) && !(isNaN(num))
      return true
    else
      return false

  valid_date =->
    day = parseInt($('#project_completion_date_3i').val())
    month = parseInt($('#project_completion_date_2i').val())
    year = parseInt($('#project_completion_date_1i').val())

    current_date = new Date()

    # apparently month is zero ordered??
    if (new Date(year, month - 1, day) < new Date(current_date.getFullYear(), current_date.getMonth(), current_date.getDate() + 7))
      return false
    else
      return true

  valid_communities =->
    if $('.communities').find('input:checked').length >= 1
      return true
    else
      return false

  valid_rewards =->
    reward_groups = $('.reward-group')

    if reward_groups == undefined
      return true
    else
      is_valid = true
      for reward in reward_groups
        do ->
          if ($(reward).find('.reward-level').val() == "") || ($(reward).find('.reward-description').val() == "")
            is_valid = false

      return is_valid

  reward_validator = (value) ->
    if value
      $('#rewards_error').addClass('hidden')
    else
      $('#rewards_error').removeClass('hidden')

  empty_content_validator = (value, ref, icon, error_text) ->
    if value
      ref.removeClass('has-error')
      $(error_text).addClass('hidden')
      field_span = ref.parent().find(icon)
      field_span.removeClass("glyphicon glyphicon-asterisk fa fa-exclamation-circle")
      field_span.addClass("fa fa-check")
    else
      ref.addClass('has-error')
      $(error_text).removeClass('hidden')
      field_span = ref.parent().find(icon)
      field_span.removeClass("glyphicon glyphicon-asterisk fa fa-check")
      field_span.addClass("fa fa-exclamation-circle")

  money_validator = (value, ref, icon, error_text) ->
    if value
      ref.removeClass('has-error')
      $(error_text).addClass('hidden')
      field_span = ref.parent().find(icon)
      field_span.removeClass("has-money-error")
      field_span.addClass("correct-money")
    else
      ref.addClass('has-error')
      $(error_text).removeClass('hidden')
      field_span = ref.parent().find(icon)
      field_span.removeClass("correct-money")
      field_span.addClass("has-money-error")

  date_validator = (value, error_text) ->
    if value
      $('#completion_date_icon').addClass('fa fa-check hidden')
      $('#completion_date_icon').removeClass('fa fa-exclamation-circle')
      $('#project_completion_date_3i, #project_completion_date_2i, #project_completion_date_1i').removeClass('has-error-select')
      $(error_text).addClass('hidden')
    else
      $('#completion_date_icon').removeClass('fa fa-check')
      $('#completion_date_icon').addClass('fa fa-exclamation-circle')
      $('#project_completion_date_3i, #project_completion_date_2i, #project_completion_date_1i').addClass('has-error-select')
      $(error_text).removeClass('hidden')

  communities_validator = (value) ->
    if value
      $('#communities_error').addClass('hidden')
    else
      $('#communities_error').removeClass('hidden')