CommunityFund/config/routes.rb
Rails.application.routes.draw do
  # devise overrides
  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}

  root "home#index"

  #dashboard
  get 'dashboard' => 'dashboard#index'
  get 'users/:username' => 'users#show', as: 'users'

  #communities
  get 'communities' => 'communities#index'
  get 'communities/:id/edit_photo' => 'communities#edit_photo'
  post 'communities/:id/join' => 'communities#join'

  namespace :admin do
    get :analytics

    get :settings
    get 'settings/autocomplete',   to: :autocomplete_user_username
    post 'settings/update_admins', to: :update_admins

    get :moderation
  end

  namespace :report do
    post :dismiss
    post :project
  end

  namespace :location do
    get :countries
    get :cities
  end

  resources :communities
  resources :projects do
    member do
      post :cancel
    end
  end
  resources :funds
  resources :posts
  resources :feedbacks do
    member do
      post :submit
      post :dismiss
    end
  end

end

CommunityFund/app/views/layouts/_feedback.html.haml
- if user_signed_in?
  - @feedbacks = Feedback.open.not_dismissed.where(user_id: current_user.id)
  - if @feedbacks.count >= 1
    .row
      - @feedbacks.each do |feedback|
        - @feedback = feedback
        .col-lg-4
          = render partial: "feedbacks/feedback", locals: {can_dismiss: true}

CommunityFund/app/views/layouts/_footer.html.haml
.col-md-offset-10
  %small
    Powered by Dude Lovin' Inc.

CommunityFund/app/views/layouts/_header.html.haml
.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{data: {toggle: 'collapse', target: '#navbar-collapse'}}
        %span.sr-only Toggle navigation
        .glyphicon.glyphicon-collapse-down
      %a.navbar-brand{href: root_path} CommunityFund
    .collapse.navbar-collapse{id: 'navbar-collapse'}
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li.active
            %a.profile-picture{href: users_path(current_user.username)}
              = image_tag avatar_url(current_user, 50), class: 'img-circle profile-img'
              Logged in as #{current_user.username}
          %li
            = link_to "Start Project", new_project_path, id: 'create_project_button'
          %li.active
            = link_to "Edit Profile", edit_user_registration_path
          - if current_user.admin?
            %li{ class: 'dropdown' }
              %a{ href: '#', class: 'dropdown-toggle', role: 'button', data: { toggle: 'dropdown' } }
                Administration
                %span{ class: 'caret' }
              %ul{ class: 'dropdown-menu', role: 'menu' }
                %li= link_to "Settings", admin_settings_path
                %li= link_to "Moderation", admin_moderation_path
                %li= link_to "Analytics", admin_analytics_path
          %li
            = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li.active
            = link_to "Sign Up", new_user_registration_path
          %li
            = link_to "Login", new_user_session_path
          %li
            = link_to "Login with Facebook", user_omniauth_authorize_path(:facebook)

CommunityFund/app/views/layouts/_sidebar.html.haml
/we will need this in the future

/can be used for search filters and other things

CommunityFund/app/views/layouts/application.html.haml
!!!
%html
    %head
        %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
        %title CommunityFund
        = stylesheet_link_tag	'application', media: 'all', 'data-turbolinks-track' => true
        = javascript_include_tag '//www.google.com/jsapi', 'chartkick'
        = javascript_include_tag 'application', 'data-turbolinks-track' => true
        = csrf_meta_tags
    %body{ class: controller_name + " " + action_name }
        = render "layouts/header"
        .container
            - if notice.present?
                .notice.alert.alert-success
                    = notice
            - if alert.present?
                .alert.alert-warning
                    = alert
            = yield
        = render "layouts/footer"
        :javascript
            $(document).ready(function() {
                $.material.init();
            });
            
        